# yaml-language-server: $schema=https://schema.workspec.io/v1alpha1/resource.schema.json
apiVersion: workspec.io/v1alpha1
kind: Resource
metadata:
  slug: core-vnet
spec:
  name: 'Core Virtual Network'
  kind: vnet
  type: 'Azure Virtual Network'
  provider: azure
  resourceGroup: rg-network
  config:
    addressSpace: '10.20.0.0/16'
  source:
    kind: authored
